run:
	python q1.py
	python q2.py
	python q3.py
	python q4.py
	python q5.py
	python q6.py
	python q7.py
	python q8.py
	python q9.py
	python q10.py
	python q21.py
	python q22.py
	python q245.py
	python q26.py